### ISSUE TITLE
Explore reusable workflows instead

### ISSUE THREAD

**Issue by fregante** [fregante/ghatemplates#24]
https://docs.github.com/en/actions/using-workflows/reusing-workflows

**Comment by fregante** [comment]
Never mind, they're an inferior solution. 

- if the workflow requires customization, as `webext/release` often does, this makes it impossible without minutely customizing the source workflow
- if the workflow is [simple](https://github.com/fregante/title-to-labels-action/blob/main/workflow/labeler.yml) but has logic outside the `jobs` object, reusing just means copy-pasting anyway:

### Source

```yml
name: Labeler

on:
  pull_request:
    types: [opened, edited]
  issues:
    types: [opened, edited]

jobs:
  Label:
    runs-on: ubuntu-latest
    steps:
      - uses: fregante/title-to-labels-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### Workflow that reuses another one

All of this would need to be manually copy-pasted

```yml
name: Labeler

on:
  pull_request:
    types: [opened, edited]
  issues:
    types: [opened, edited]

jobs:
  Label:
    uses: fregante/title-to-labels-action/workflow/labeler.yml@f2268f808704e47b80fd74dc255e88f1bc5c413f
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
